### ISSUE TITLE
Add support for GTFS-RT (Realtime Data Ingestion)

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#44]
We need to add optional support to the core Docker image (hosted in `./oba`) for real-time data (i.e. GTFS-RT data sources).

Here are three guides that will help. Please note that some of the information in these may be out of date, and some may be contradictory. Please help out when you find info that should be changed and drop an issue in the [onebusaway-docs issue tracker](https://github.com/OneBusAway/onebusaway-docs/issues).

* https://developer.onebusaway.org/guides/realtime-configuration-guide - this seems to be the most up to date.
* https://developer.onebusaway.org/guides/wiki/gtfs-realtime-resources
* https://developer.onebusaway.org/guides/wiki/gtfs-realtime-quickstart

### Test Feeds

These feeds are from Community Transit, a transit agency in Everett, Washington, USA.

* Trip Updates: http://s3.amazonaws.com/commtrans-realtime-prod/tripupdates.pb
* Vehicle Positions: http://s3.amazonaws.com/commtrans-realtime-prod/vehiclepositions.pb
* Alerts: http://s3.amazonaws.com/commtrans-realtime-prod/alerts.pb

### User story

> As an IT administrator deploying a OneBusAway server
> I want to be able to specify a tripUpdatesUrl, vehiclePositionsUrl, and alertsUrl
> So that my users can get real-time data in their OBA apps.

### Subtasks

- [ ] Allow a user to _optionally_ specify trip updates, vehicle positions, and alerts URLs at runtime. If one or more of these feeds are not available, they should not be added to the appropriate data-sources.xml file. In other words, the Dockerized server works fine whether it only serves static data or real time data.
- [ ] Document the runtime behavior in an appropriate location (README?)
- [ ] Optional: Improve the real-time configuration docs in the onebusaway-docs repo.

**Comment by Altonhe** [comment]
I'd like to try on this, could you assign it to me?

**Comment by aaronbrethorst** [comment]
Thanks @Altonhe you got it!

**Comment by aaronbrethorst** [comment]
@Altonhe per the email linked to below, the appropriate realtime bean config XML should go in the onebusaway-transit-data-federation-webapp data-sources.xml file. 

https://groups.google.com/d/msgid/onebusaway-developers/CAOb6mHDy6pGR517LSC_31PZ3bJ3nMyb57UmAGDaW42nDG3WDFw%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by aaronbrethorst** [comment]
Fixed in #58 - thank you @Altonhe
